"""
PRDescriptionGenerator - Generates structured, evidence-backed GitHub Pull Request descriptions for AgentOS-SWE (M5).
"""

import logging
from typing import Dict, Any, Optional

from agentos_swe.core.models import Finding
from agentos_swe.remediation.repair.models import ValidatedPatch
from agentos_swe.remediation.pr.models import RiskAssessment

logger = logging.getLogger(__name__)


class PRDescriptionGenerator:
    """
    Generates structured, verifiable markdown PR descriptions.
    """

    def generate_pr_payload(
        self,
        finding: Finding,
        patch: ValidatedPatch,
        risk: RiskAssessment,
        branch_name: str,
    ) -> Dict[str, str]:
        title = f"fix(agentos-swe): resolve {finding.category} flaw - {finding.title}"

        risk_signals_md = "\n".join([f"- {s}" for s in risk.risk_signals]) if risk.risk_signals else "- None detected."
        changed_files_md = "\n".join([f"- `{f}`" for f in patch.changed_files]) if patch.changed_files else "- None"

        repro_status = "PASS" if patch.reproduction_result.get("success") else "FAIL"
        regress_status = "PASS" if patch.regression_result.get("success") else "FAIL"
        review_status = patch.review_result.status if hasattr(patch.review_result, "status") else "APPROVED"

        body = f"""## 🤖 AgentOS-SWE Automated Repair Patch

> [!IMPORTANT]
> **Human Review Required**: This pull request was autonomously generated, verified in an isolated sandbox, and approved by AgentOS Governance Engine. It requires final human review before merging.

---

### 📌 Finding Overview
- **Title**: {finding.title}
- **Category**: `{finding.category}`
- **Severity**: `{finding.severity.upper()}`
- **Target File**: `{finding.file}`
- **Finding ID**: `{finding.id}`

---

### 🛡️ Risk Assessment & Governance
- **Risk Level**: `{risk.risk_level.value}` (Score: `{risk.risk_score:.1f}`)
- **Governance Decision**: `APPROVED FOR PR`
- **Risk Signals**:
{risk_signals_md}

---

### 📊 Verification & Validation Results
- **Reproduction Test**: `{repro_status}`
- **Regression Tests**: `{regress_status}`
- **Independent Code Review**: `{review_status}`

---

### 📁 Scope of Changes
**Changed Files**:
{changed_files_md}

**Unified Patch Diff**:
```diff
{patch.patch_diff}
```

---
*Generated by **AgentOS-SWE (Autonomous Software Verification and Repair System)**.*
"""
        return {"title": title, "body": body}
