"""
AgentOS CLI - Typer-based command line interface for project scaffolding, validation, and execution.
"""

import os
import sys
import yaml
import glob
import importlib.util
import logging
from typing import List, Optional
import typer
from rich.console import Console
from rich.table import Table
from rich.syntax import Syntax
from rich import print as rprint

from agentos.core.config_models import (
    ProjectConfig,
    AgentYAMLConfig,
    ToolYAMLConfig,
    CrewYAMLConfig,
    MissionYAMLConfig,
    TaskYAMLConfig
)
from agentos.core.base import AgentRegistry, ToolRegistry, BaseAgent, BaseTool, BaseMemory
from agentos.core.agent import Agent
from agentos.core.squad import Squad, SquadRole, Mission
from agentos.core.planner import TaskGraph, TaskNode
from agentos.core.governance import GovernanceEngine
from agentos.core.checkpoint import SQLiteCheckpointStore
from agentos.llm import LLMClient
from agentos.mcp.plugin_loader import discover_plugins, load_plugin
from agentos.builder.agent_builder import AgentBuilder
from agentos.builder.tool_builder import ToolBuilder
from agentos.builder.crew_builder import CrewBuilder

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("agentos.cli")

app = typer.Typer(help="AgentOS Framework CLI")
console = Console()

def to_camel_case(snake_str: str) -> str:
    """Helper to convert snake_case names to CamelCase class names"""
    return "".join(x.title() for x in snake_str.split("_"))

# =====================================================================
# CLI COMMANDS - Scaffold & Validation
# =====================================================================

@app.command("new-project")
def new_project(project_name: str):
    """
    Creates a new AgentOS project directory with scaffolding templates.
    """
    if os.path.exists(project_name):
        console.print(f"[bold red]Error:[/bold red] Directory '{project_name}' already exists.")
        raise typer.Exit(code=1)
        
    # Scaffold directories
    dirs = [
        "",
        "agents",
        "tools",
        "mcp_plugins",
        "crews",
        "missions",
        "memory",
        "checkpoints"
    ]
    for d in dirs:
        os.makedirs(os.path.join(project_name, d), exist_ok=True)
        
    # Write default agentos.config.yaml
    config_content = {
        "preferred_tags": ["fast"],
        "default_model": "gpt-4o-mini"
    }
    with open(os.path.join(project_name, "agentos.config.yaml"), "w", encoding="utf-8") as f:
        yaml.safe_dump(config_content, f)
        
    # Write .gitignore
    gitignore = ".env\ncheckpoints/\nmemory/\n__pycache__/\n*.pyc\n"
    with open(os.path.join(project_name, ".gitignore"), "w", encoding="utf-8") as f:
        f.write(gitignore)
        
    # Scaffolding default templates
    # Agent Template
    default_agent = {
        "name": "GeneralAssistant",
        "role": "Helpful AI Assistant",
        "goal": "Answer user queries accurately",
        "backstory": "A professional AI designed to be supportive.",
        "llm_tags": ["fast"],
        "tool_refs": [],
        "memory_ref": None
    }
    with open(os.path.join(project_name, "agents", "general_assistant.yaml"), "w", encoding="utf-8") as f:
        yaml.safe_dump(default_agent, f)
        
    # README.md
    readme = (
        f"# {project_name}\n\n"
        "This is an autogenerated AgentOS multi-agent project.\n\n"
        "## Structure\n"
        "- `agentos.config.yaml`: Project configuration, tags, and defaults.\n"
        "- `agents/`: Agent configuration YAML files.\n"
        "- `tools/`: Custom Python tool implementations.\n"
        "- `mcp_plugins/`: Third-party addon plugin packages.\n"
        "- `crews/`: Crew orchestrators.\n"
        "- `missions/`: Mission definitions (task lists).\n"
        "- `checkpoints/`: Local run state database for checkpointing.\n\n"
        "## Usage\n"
        "Run a mission: `agentos run . --mission <mission_name>`\n"
    )
    with open(os.path.join(project_name, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)
        
    # Scaffolding empty .env
    with open(os.path.join(project_name, ".env"), "w", encoding="utf-8") as f:
        f.write("# Environment keys go here\n")

    console.print(f"[bold green]Success:[/bold green] Project '{project_name}' created successfully.")


@app.command("new-agent")
def new_agent(
    project_path: str,
    name: str = typer.Option(..., help="Alphanumeric name of the agent"),
    role: str = typer.Option(..., help="Role specification"),
    goal: str = typer.Option(..., help="Goal specification")
):
    """
    Appends a new Pydantic-validated agent YAML configuration under agents/.
    """
    try:
        config = AgentYAMLConfig(
            name=name,
            role=role,
            goal=goal,
            backstory=f"A helpful {role} focused on: {goal}.",
            llm_tags=["fast"],
            tool_refs=[],
            memory_ref=None
        )
    except Exception as e:
        console.print(f"[bold red]Validation Error:[/bold red]\n{e}")
        raise typer.Exit(code=1)
        
    file_name = f"{name.lower().replace(' ', '_')}.yaml"
    dest_path = os.path.join(project_path, "agents", file_name)
    
    with open(dest_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(config.model_dump(), f)
        
    console.print(f"[bold green]Success:[/bold green] Created agent '{name}' at {dest_path}")


@app.command("new-tool")
def new_tool(
    project_path: str,
    name: str = typer.Option(..., help="Lowercase snake_case name of the tool")
):
    """
    Scaffolds a Python class stub for a BaseTool subclass in tools/.
    """
    class_name = to_camel_case(name)
    tool_content = (
        "\"\"\"\n"
        f"Custom Tool: {class_name}\n"
        "\"\"\"\n\n"
        "from agentos.core.base import BaseTool\n\n"
        f"class {class_name}(BaseTool):\n"
        f"    name: str = \"{name}\"\n"
        f"    description: str = \"TODO: Provide detailed description of this tool's behavior.\"\n\n"
        "    def run(self, **kwargs) -> str:\n"
        "        # TODO: Implement tool business logic\n"
        "        query = kwargs.get('query', '')\n"
        "        return f\"Stub tool executed with query: {query}\"\n"
    )
    
    dest_path = os.path.join(project_path, "tools", f"{name}.py")
    with open(dest_path, "w", encoding="utf-8") as f:
        f.write(tool_content)
        
    console.print(f"[bold green]Success:[/bold green] Scaffolded tool '{class_name}' at {dest_path}")


@app.command("new-crew")
def new_crew(
    project_path: str,
    name: str = typer.Option(..., help="Name of the crew"),
    agents: str = typer.Option(..., help="Comma-separated agent names to include"),
    process: str = typer.Option("sequential", help="Process type: sequential or hierarchical")
):
    """
    Creates a new crew YAML configuration validating agent names.
    """
    agent_names = [a.strip() for a in agents.split(",") if a.strip()]
    
    # Validate agent names exist
    agents_dir = os.path.join(project_path, "agents")
    existing_agents = []
    if os.path.exists(agents_dir):
        for file in glob.glob(os.path.join(agents_dir, "*.yaml")):
            with open(file, "r", encoding="utf-8") as f:
                try:
                    data = yaml.safe_load(f)
                    existing_agents.append(data.get("name"))
                except:
                    pass
                    
    for a in agent_names:
        if a not in existing_agents:
            console.print(f"[bold red]Error:[/bold red] Agent '{a}' is not defined in any YAML files under agents/.")
            raise typer.Exit(code=1)
            
    config = CrewYAMLConfig(name=name, agents=agent_names, process=process)
    dest_path = os.path.join(project_path, "crews", f"{name.lower().replace(' ', '_')}.yaml")
    
    with open(dest_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(config.model_dump(), f)
        
    console.print(f"[bold green]Success:[/bold green] Created crew '{name}' at {dest_path}")


@app.command("new-mcp-plugin")
def new_mcp_plugin(
    project_path: str,
    name: str = typer.Option(..., help="Name of the MCP plugin")
):
    """
    Scaffolds a Model Context Protocol third-party plugin directory template.
    """
    plugin_dir = os.path.join(project_path, "mcp_plugins", name)
    if os.path.exists(plugin_dir):
        console.print(f"[bold red]Error:[/bold red] Plugin directory '{name}' already exists.")
        raise typer.Exit(code=1)
        
    os.makedirs(plugin_dir, exist_ok=True)
    
    # manifest.yaml
    manifest = {
        "name": name,
        "version": "1.0.0",
        "author": "Developer",
        "permissions": [],
        "entrypoint": "plugin.MyMCPPlugin",
        "mcp_server_url": None
    }
    with open(os.path.join(plugin_dir, "manifest.yaml"), "w", encoding="utf-8") as f:
        yaml.safe_dump(manifest, f)
        
    # plugin.py
    plugin_stub = (
        "from agentos.core.base import BaseMCPPlugin, BaseTool\n"
        "from typing import List\n\n"
        "class MyMCPPlugin(BaseMCPPlugin):\n"
        "    def register_tools(self) -> List[BaseTool]:\n"
        "        # TODO: Implement and return plugin tools\n"
        "        return []\n"
    )
    with open(os.path.join(plugin_dir, "plugin.py"), "w", encoding="utf-8") as f:
        f.write(plugin_stub)
        
    console.print(f"[bold green]Success:[/bold green] Scaffolded MCP plugin at {plugin_dir}")


@app.command("validate")
def validate(project_path: str):
    """
    Validates all project YAML files against Pydantic schemas without executing them.
    """
    errors = 0
    
    # 1. Validate agentos.config.yaml
    config_file = os.path.join(project_path, "agentos.config.yaml")
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
            ProjectConfig(**data)
            console.print(f"[green]OK[/green] Config validated: {config_file}")
        except Exception as e:
            console.print(f"[bold red]ERROR in {config_file}:[/bold red]\n{e}")
            errors += 1
            
    # 2. Validate agents/
    agents_dir = os.path.join(project_path, "agents")
    if os.path.exists(agents_dir):
        for fpath in glob.glob(os.path.join(agents_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                AgentYAMLConfig(**data)
                console.print(f"[green]OK[/green] Agent validated: {fpath}")
            except Exception as e:
                console.print(f"[bold red]ERROR in {fpath}:[/bold red]\n{e}")
                errors += 1
                
    # 3. Validate crews/
    crews_dir = os.path.join(project_path, "crews")
    if os.path.exists(crews_dir):
        for fpath in glob.glob(os.path.join(crews_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                CrewYAMLConfig(**data)
                console.print(f"[green]OK[/green] Crew validated: {fpath}")
            except Exception as e:
                console.print(f"[bold red]ERROR in {fpath}:[/bold red]\n{e}")
                errors += 1
                
    # 4. Validate missions/
    missions_dir = os.path.join(project_path, "missions")
    if os.path.exists(missions_dir):
        for fpath in glob.glob(os.path.join(missions_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                MissionYAMLConfig(**data)
                console.print(f"[green]OK[/green] Mission validated: {fpath}")
            except Exception as e:
                console.print(f"[bold red]ERROR in {fpath}:[/bold red]\n{e}")
                errors += 1

    if errors > 0:
        console.print(f"\n[bold red]Validation failed with {errors} errors.[/bold red]")
        raise typer.Exit(code=1)
    else:
        console.print("\n[bold green]Validation passed successfully![/bold green]")

# =====================================================================
# CLI COMMANDS - List Info
# =====================================================================

@app.command("list-agents")
def list_agents(project_path: str):
    """List all defined agents."""
    table = Table(title="Project Agents")
    table.add_column("Name", style="cyan")
    table.add_column("Role", style="magenta")
    table.add_column("Goal", style="green")
    
    agents_dir = os.path.join(project_path, "agents")
    if os.path.exists(agents_dir):
        for fpath in glob.glob(os.path.join(agents_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                table.add_row(data.get("name", ""), data.get("role", ""), data.get("goal", ""))
            except:
                pass
    console.print(table)


@app.command("list-tools")
def list_tools(project_path: str):
    """List all custom tools."""
    table = Table(title="Project Custom Tools")
    table.add_column("Class Name", style="cyan")
    table.add_column("File Name", style="magenta")
    
    tools_dir = os.path.join(project_path, "tools")
    if os.path.exists(tools_dir):
        for fpath in glob.glob(os.path.join(tools_dir, "*.py")):
            table.add_row(to_camel_case(os.path.basename(fpath)[:-3]), os.path.basename(fpath))
    console.print(table)


@app.command("list-crews")
def list_crews(project_path: str):
    """List all defined crews."""
    table = Table(title="Project Crews")
    table.add_column("Crew Name", style="cyan")
    table.add_column("Agents", style="magenta")
    table.add_column("Process", style="green")
    
    crews_dir = os.path.join(project_path, "crews")
    if os.path.exists(crews_dir):
        for fpath in glob.glob(os.path.join(crews_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                table.add_row(data.get("name", ""), ", ".join(data.get("agents", [])), data.get("process", "sequential"))
            except:
                pass
    console.print(table)


@app.command("list-missions")
def list_missions(project_path: str):
    """List all defined missions."""
    table = Table(title="Project Missions")
    table.add_column("Mission Name", style="cyan")
    table.add_column("Goal", style="green")
    table.add_column("Crew", style="magenta")
    
    missions_dir = os.path.join(project_path, "missions")
    if os.path.exists(missions_dir):
        for fpath in glob.glob(os.path.join(missions_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                table.add_row(data.get("name", ""), data.get("goal", ""), data.get("crew", ""))
            except:
                pass
    console.print(table)

# =====================================================================
# CLI COMMANDS - Run Execution
# =====================================================================

@app.command("run")
def run_project(
    project_path: str,
    mission_name: str = typer.Option(..., "--mission", help="Name of the mission config to run"),
    resume: bool = typer.Option(False, help="Resume execution from latest checkpoint")
):
    """
    Executes a project mission, loading config, resolving tools/plugins, and checkpointing.
    """
    # 1. Load project configurations
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    # Load dotenv from project directory if exists
    dotenv_path = os.path.join(project_path, ".env")
    if os.path.exists(dotenv_path):
        from dotenv import load_dotenv
        load_dotenv(dotenv_path)

    # 2. Build registries
    tool_registry = ToolRegistry()
    agent_registry = AgentRegistry()
    
    # 3. Discover and load MCP plugins
    discovered_plugins = discover_plugins(project_path)
    for manifest, m_path in discovered_plugins:
        try:
            load_plugin(manifest, m_path, tool_registry)
        except Exception as e:
            console.print(f"[bold yellow]Warning:[/bold yellow] Failed to load MCP plugin '{manifest.name}': {e}")
            
    # 4. Load custom python tools from tools/
    tools_dir = os.path.join(project_path, "tools")
    if os.path.exists(tools_dir):
        for py_file in glob.glob(os.path.join(tools_dir, "*.py")):
            try:
                spec = importlib.util.spec_from_file_location("dynamic_tool", py_file)
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                
                for attr_name in dir(module):
                    attr = getattr(module, attr_name)
                    if isinstance(attr, type) and issubclass(attr, BaseTool) and attr is not BaseTool:
                        tool_registry.register(attr)
            except Exception as e:
                console.print(f"[bold yellow]Warning:[/bold yellow] Failed to load python tool from {py_file}: {e}")

    # 5. Initialize LLMClient
    llm_client = LLMClient(preferred_tags=preferred_tags)
    
    # 6. Load agent definitions from agents/
    agents_map = {}
    agents_dir = os.path.join(project_path, "agents")
    if os.path.exists(agents_dir):
        for fpath in glob.glob(os.path.join(agents_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                agent_cfg = AgentYAMLConfig(**data)
                
                # Resolve tools for this agent
                agent_tools = []
                for ref in agent_cfg.tool_refs:
                    try:
                        t_inst = tool_registry.create(ref)
                        agent_tools.append(t_inst)
                    except Exception as e:
                        # Fallback try camel case class names
                        camel_ref = to_camel_case(ref)
                        try:
                            t_inst = tool_registry.create(camel_ref)
                            agent_tools.append(t_inst)
                        except:
                            console.print(f"[bold yellow]Warning:[/bold yellow] Tool '{ref}' not found in registry for agent '{agent_cfg.name}'")
                
                # Create agent
                agent = Agent(
                    name=agent_cfg.name,
                    role=agent_cfg.role,
                    goal=agent_cfg.goal,
                    backstory=agent_cfg.backstory,
                    llm_client=llm_client,
                    tools=agent_tools
                )
                agents_map[agent_cfg.name] = agent
            except Exception as e:
                console.print(f"[bold red]Error loading agent configuration {fpath}:[/bold red] {e}")
                raise typer.Exit(code=1)

    # 7. Load Mission config
    mission_file = os.path.join(project_path, "missions", f"{mission_name}.yaml")
    if not os.path.exists(mission_file):
        # Try without lowercase/underscores conversion
        mission_file = os.path.join(project_path, "missions", f"{mission_name.lower().replace(' ', '_')}.yaml")
        if not os.path.exists(mission_file):
            console.print(f"[bold red]Error:[/bold red] Mission config '{mission_name}' not found under missions/.")
            raise typer.Exit(code=1)
            
    with open(mission_file, "r", encoding="utf-8") as f:
        m_data = yaml.safe_load(f)
    mission_cfg = MissionYAMLConfig(**m_data)

    # 8. Load Crew config
    crew_file = os.path.join(project_path, "crews", f"{mission_cfg.crew.lower().replace(' ', '_')}.yaml")
    if not os.path.exists(crew_file):
        console.print(f"[bold red]Error:[/bold red] Crew config '{mission_cfg.crew}' not found under crews/.")
        raise typer.Exit(code=1)
        
    with open(crew_file, "r", encoding="utf-8") as f:
        c_data = yaml.safe_load(f)
    crew_cfg = CrewYAMLConfig(**c_data)

    # 9. Instantiate checkpoint store and Governance
    checkpoint_db = os.path.join(project_path, "checkpoints", "run_history.db")
    checkpoint_store = SQLiteCheckpointStore(db_path=checkpoint_db)
    
    governance = GovernanceEngine()
    squad = Squad(name=crew_cfg.name, checkpoint_store=checkpoint_store, governance=governance)
    
    # Add agents to squad matching the roles
    for a_name in crew_cfg.agents:
        if a_name not in agents_map:
            console.print(f"[bold red]Error:[/bold red] Agent '{a_name}' defined in Crew is missing from agents/ definitions.")
            raise typer.Exit(code=1)
        # Check if agent should be commander (hierarchical)
        role = SquadRole.WORKER
        if crew_cfg.process == "hierarchical" and a_name == crew_cfg.agents[0]:
            role = SquadRole.COMMANDER
        squad.add_agent(agents_map[a_name], role)
        
    # Build task graph
    task_nodes = []
    for idx, t in enumerate(mission_cfg.tasks):
        # Match assigned agent name
        assigned_id = None
        if t.assigned_agent:
            agent_inst = agents_map.get(t.assigned_agent)
            if agent_inst:
                assigned_id = agent_inst.id
                
        task_nodes.append(TaskNode(
            id=f"t_{idx}",
            description=t.description,
            assigned_agent=assigned_id
        ))
    task_graph = TaskGraph(id=f"tg_{mission_name}", goal=mission_cfg.goal, nodes=task_nodes)
    
    mission = Mission(
        id=mission_cfg.name,
        goal=mission_cfg.goal,
        description=mission_cfg.description,
        task_graph=task_graph
    )
    
    # 10. Run mission
    console.print(f"[bold blue]Running mission:[/bold blue] {mission_cfg.name} (resume={resume})...")
    try:
        result = squad.run_mission(mission, resume=resume)
        console.print("\n[bold green]Mission executed successfully! Output:[/bold green]")
        console.print(result)
    except Exception as e:
        console.print(f"\n[bold red]Mission execution failed:[/bold red] {e}")
        raise typer.Exit(code=1)

# =====================================================================
# CLI COMMANDS - Natural Language Builders
# =====================================================================

@app.command("build-agent")
def build_agent(
    project_path: str,
    describe: str = typer.Option(..., help="Natural language description of the agent")
):
    """
    Proposes agent configuration via LLM and writes to agents/ after confirmation.
    """
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    llm_client = LLMClient(preferred_tags=preferred_tags)
    builder = AgentBuilder(llm_client=llm_client)
    
    console.print("[bold blue]Proposing Agent configuration via LLM...[/bold blue]")
    try:
        proposed = builder.create_from_description(describe)
    except Exception as e:
        console.print(f"[bold red]LLM Generation failed:[/bold red] {e}")
        raise typer.Exit(code=1)
        
    yaml_str = yaml.safe_dump(proposed, default_flow_style=False)
    console.print("\n[bold yellow]Proposed Agent YAML:[/bold yellow]")
    console.print(Syntax(yaml_str, "yaml", theme="monokai", line_numbers=True))
    
    confirm = typer.confirm("Do you want to write this configuration to agents/?")
    if confirm:
        file_name = f"{proposed['name'].lower().replace(' ', '_')}.yaml"
        dest_path = os.path.join(project_path, "agents", file_name)
        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(yaml_str)
        console.print(f"[bold green]Success:[/bold green] Wrote Agent config to {dest_path}")
    else:
        console.print("[yellow]Cancelled configuration write.[/yellow]")


@app.command("build-tool")
def build_tool(
    project_path: str,
    describe: str = typer.Option(..., help="Natural language description of what the tool should do")
):
    """
    Proposes custom python tool stubs via LLM and writes to tools/ after confirmation.
    """
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    llm_client = LLMClient(preferred_tags=preferred_tags)
    builder = ToolBuilder(llm_client=llm_client)
    
    console.print("[bold blue]Proposing Custom Tool stub via LLM...[/bold blue]")
    try:
        config, py_code = builder.create_from_description(describe)
    except Exception as e:
        console.print(f"[bold red]LLM Generation failed:[/bold red] {e}")
        raise typer.Exit(code=1)
        
    console.print("\n[bold yellow]Proposed Python Tool Stub Code:[/bold yellow]")
    console.print(Syntax(py_code, "python", theme="monokai", line_numbers=True))
    
    confirm = typer.confirm("Do you want to write this tool code to tools/?")
    if confirm:
        dest_path = os.path.join(project_path, "tools", f"{config['name']}.py")
        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(py_code)
        console.print(f"[bold green]Success:[/bold green] Wrote Custom Tool stub to {dest_path}")
    else:
        console.print("[yellow]Cancelled tool stub write.[/yellow]")


@app.command("build-crew")
def build_crew(
    project_path: str,
    describe: str = typer.Option(..., help="Natural language overall project goal description")
):
    """
    Proposes entire crew orchestrations (crews, agents, and task lists) via LLM.
    """
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    llm_client = LLMClient(preferred_tags=preferred_tags)
    builder = CrewBuilder(llm_client=llm_client)
    
    console.print("[bold blue]Proposing Crew Orchestration design via LLM...[/bold blue]")
    try:
        proposed = builder.create_from_goal(describe)
    except Exception as e:
        console.print(f"[bold red]LLM Generation failed:[/bold red] {e}")
        raise typer.Exit(code=1)
        
    json_str = json.dumps(proposed, indent=2)
    console.print("\n[bold yellow]Proposed Crew Structure (JSON):[/bold yellow]")
    console.print(Syntax(json_str, "json", theme="monokai", line_numbers=True))
    
    confirm = typer.confirm("Do you want to write these proposed Agent, Crew, and Mission configurations to disk?")
    if confirm:
        # 1. Write agents
        for a in proposed["agents"]:
            a_cfg = {
                "name": a["name"],
                "role": a["role"],
                "goal": a["goal"],
                "backstory": a["backstory"],
                "llm_tags": ["fast"],
                "tool_refs": a.get("suggested_tools", []),
                "memory_ref": None
            }
            a_file = os.path.join(project_path, "agents", f"{a['name'].lower().replace(' ', '_')}.yaml")
            with open(a_file, "w", encoding="utf-8") as f:
                yaml.safe_dump(a_cfg, f)
            console.print(f"[green]OK[/green] Wrote Agent definition: {a_file}")
            
        # 2. Write Crew
        c_names = [a["name"] for a in proposed["agents"]]
        c_cfg = {
            "name": proposed["name"],
            "agents": c_names,
            "process": proposed.get("process", "sequential")
        }
        c_file = os.path.join(project_path, "crews", f"{proposed['name'].lower().replace(' ', '_')}.yaml")
        with open(c_file, "w", encoding="utf-8") as f:
            yaml.safe_dump(c_cfg, f)
        console.print(f"[green]OK[/green] Wrote Crew definition: {c_file}")
        
        # 3. Write Mission
        m_tasks = []
        for t in proposed["tasks"]:
            m_tasks.append({
                "description": t["description"],
                "assigned_agent": t["assigned_agent"]
            })
        m_cfg = {
            "name": f"{proposed['name']}Mission",
            "goal": describe,
            "description": f"Auto-generated mission for crew: {proposed['name']}",
            "crew": proposed["name"],
            "tasks": m_tasks
        }
        m_file = os.path.join(project_path, "missions", f"{proposed['name'].lower().replace(' ', '_')}_mission.yaml")
        with open(m_file, "w", encoding="utf-8") as f:
            yaml.safe_dump(m_cfg, f)
        console.print(f"[green]OK[/green] Wrote Mission definition: {m_file}")
        
        console.print("[bold green]Success: All proposed configs written to disk successfully.[/bold green]")
    else:
        console.print("[yellow]Cancelled configuration write.[/yellow]")


# =====================================================================
# PACKAGING COMMANDS (Phase 3)
# =====================================================================

pack_app = typer.Typer(help="Build, sign, verify, and install .agentpack bundles")
app.add_typer(pack_app, name="pack")


@app.command("keygen")
def keygen(
    keys_dir: Optional[str] = typer.Option(None, help="Directory to write keys (default: ~/.agentos/keys/)"),
):
    """Generate an Ed25519 keypair for signing .agentpack files."""
    from agentos.packaging.signer import generate_keypair
    priv, pub = generate_keypair(keys_dir=keys_dir)
    console.print(f"[green]OK[/green] Private key: {priv}")
    console.print(f"[green]OK[/green] Public key:  {pub}")
    console.print("[bold yellow]WARNING: Never commit private.pem to version control.[/bold yellow]")


@pack_app.command("build")
def pack_build(
    project_path: str = typer.Argument(".", help="AgentOS project directory to pack"),
    agents: str = typer.Option("", help="Comma-separated agent names to include"),
    tools: str = typer.Option("", help="Comma-separated tool names to include"),
    crews: str = typer.Option("", help="Comma-separated crew names to include"),
    output: str = typer.Option("bundle.agentpack", help="Output .agentpack file path"),
):
    """Build a .agentpack file from a project directory."""
    from agentos.packaging.pack_format import build_pack
    include = {
        "agents": [s.strip() for s in agents.split(",") if s.strip()],
        "tools": [s.strip() for s in tools.split(",") if s.strip()],
        "crews": [s.strip() for s in crews.split(",") if s.strip()],
    }
    result = build_pack(project_path=os.path.abspath(project_path), include=include, output_path=output)
    console.print(f"[green]OK[/green] Pack built: {result}")


@pack_app.command("sign")
def pack_sign(
    pack_path: str = typer.Argument(..., help="Path to .agentpack file"),
    key: str = typer.Option(None, help="Path to private.pem (default: ~/.agentos/keys/private.pem)"),
):
    """Sign a .agentpack file with your Ed25519 private key."""
    from agentos.packaging.signer import sign_pack
    from pathlib import Path
    key_path = key or str(Path.home() / ".agentos" / "keys" / "private.pem")
    sign_pack(pack_path=pack_path, private_key_path=key_path)
    console.print(f"[green]OK[/green] Pack signed: {pack_path}")


@pack_app.command("verify")
def pack_verify(
    pack_path: str = typer.Argument(..., help="Path to .agentpack file"),
):
    """Verify the Ed25519 signature of a .agentpack file."""
    from agentos.packaging.signer import verify_pack, get_signer_fingerprint
    valid = verify_pack(pack_path)
    if valid:
        fp = get_signer_fingerprint(pack_path)
        console.print(f"[green]VALID[/green] Signature verified. Signer fingerprint: {fp}")
    else:
        console.print("[bold red]INVALID[/bold red] Signature verification failed or pack is unsigned.")
        raise typer.Exit(code=1)


@pack_app.command("install")
def pack_install(
    pack_path: str = typer.Argument(..., help="Path to .agentpack file"),
    target: str = typer.Argument(..., help="Target AgentOS project directory"),
    force: bool = typer.Option(False, "--force", help="Overwrite existing files"),
    license_key: Optional[str] = typer.Option(None, "--license-key", help="License key for commercial packs"),
):
    """Install a .agentpack into an AgentOS project directory."""
    from agentos.packaging.pack_format import install_pack
    try:
        result = install_pack(pack_path=pack_path, target_project=target, force=force, license_key=license_key)
        console.print(f"[green]OK[/green] Installed pack '{result['pack']}' v{result['version']}")
        for category, items in result["installed"].items():
            if items:
                console.print(f"  {category}: {', '.join(str(i) for i in items)}")
    except PermissionError as e:
        console.print(f"[bold red]LICENSE ERROR:[/bold red] {e}")
        raise typer.Exit(code=1)
    except FileExistsError as e:
        console.print(f"[bold red]CONFLICT:[/bold red] {e}")
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
