"""
AgentOS CLI - Typer-based command line interface for project scaffolding, validation, and execution.
"""

import os
import json
import yaml
import glob
import logging
from typing import Optional
import typer
from rich.console import Console
from rich.table import Table
from rich.syntax import Syntax

from agentos.core.config_models import (
    ProjectConfig,
    AgentYAMLConfig,
    CrewYAMLConfig,
    MissionYAMLConfig
)
from agentos.core.base import AgentRegistry, ToolRegistry
from agentos.core.checkpoint import SQLiteCheckpointStore
from agentos.llm import LLMClient
from agentos.builder.agent_builder import AgentBuilder
from agentos.builder.tool_builder import ToolBuilder
from agentos.builder.crew_builder import CrewBuilder
from agentos.core.bootstrap import register_builtin_components

from agentos.core.logging_config import setup_logging
setup_logging()
logger = logging.getLogger("agentos.cli")

app = typer.Typer(help="AgentOS Framework CLI")
console = Console()

# Register all built-in components at CLI startup
register_builtin_components()

def version_callback(value: bool):
    if value:
        from agentos.__version__ import __version__
        console.print(f"AgentOS v{__version__}")
        raise typer.Exit()

@app.callback()
def main_callback(
    version: Optional[bool] = typer.Option(
        None,
        "--version",
        "-v",
        help="Show version and exit",
        callback=version_callback,
        is_eager=True,
    ),
):
    pass


def to_camel_case(snake_str: str) -> str:
    """Helper to convert snake_case names to CamelCase class names"""
    return "".join(x.title() for x in snake_str.split("_"))

# =====================================================================
# CLI COMMANDS - Scaffold & Validation
# =====================================================================

@app.command("new-project")
def new_project(project_name: str):
    """
    Creates a new AgentOS project directory with scaffolding templates.
    """
    if os.path.exists(project_name):
        console.print(f"[bold red]Error:[/bold red] Directory '{project_name}' already exists.")
        raise typer.Exit(code=1)
        
    # Scaffold directories
    dirs = [
        "",
        "agents",
        "tools",
        "mcp_plugins",
        "crews",
        "missions",
        "memory",
        "checkpoints"
    ]
    for d in dirs:
        os.makedirs(os.path.join(project_name, d), exist_ok=True)
        
    # Write default agentos.config.yaml
    config_content = {
        "preferred_tags": ["fast"],
        "default_model": "gpt-4o-mini"
    }
    with open(os.path.join(project_name, "agentos.config.yaml"), "w", encoding="utf-8") as f:
        yaml.safe_dump(config_content, f)
        
    # Write .gitignore
    gitignore = ".env\ncheckpoints/\nmemory/\n__pycache__/\n*.pyc\n"
    with open(os.path.join(project_name, ".gitignore"), "w", encoding="utf-8") as f:
        f.write(gitignore)
        
    # Scaffolding default templates
    # Agent Template
    default_agent = {
        "name": "GeneralAssistant",
        "role": "Helpful AI Assistant",
        "goal": "Answer user queries accurately",
        "backstory": "A professional AI designed to be supportive.",
        "llm_tags": ["fast"],
        "tool_refs": [],
        "memory_ref": None
    }
    with open(os.path.join(project_name, "agents", "general_assistant.yaml"), "w", encoding="utf-8") as f:
        yaml.safe_dump(default_agent, f)
        
    # README.md
    readme = (
        f"# {project_name}\n\n"
        "This is an autogenerated AgentOS multi-agent project.\n\n"
        "## Structure\n"
        "- `agentos.config.yaml`: Project configuration, tags, and defaults.\n"
        "- `agents/`: Agent configuration YAML files.\n"
        "- `tools/`: Custom Python tool implementations.\n"
        "- `mcp_plugins/`: Third-party addon plugin packages.\n"
        "- `crews/`: Crew orchestrators.\n"
        "- `missions/`: Mission definitions (task lists).\n"
        "- `checkpoints/`: Local run state database for checkpointing.\n\n"
        "## Usage\n"
        "Run a mission: `agentos run . --mission <mission_name>`\n"
    )
    with open(os.path.join(project_name, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)
        
    # Scaffolding empty .env
    with open(os.path.join(project_name, ".env"), "w", encoding="utf-8") as f:
        f.write("# Environment keys go here\n")

    console.print(f"[bold green]Success:[/bold green] Project '{project_name}' created successfully.")


@app.command("new-agent")
def new_agent(
    project_path: str,
    name: str = typer.Option(..., help="Alphanumeric name of the agent"),
    role: str = typer.Option(..., help="Role specification"),
    goal: str = typer.Option(..., help="Goal specification")
):
    """
    Appends a new Pydantic-validated agent YAML configuration under agents/.
    """
    try:
        config = AgentYAMLConfig(
            name=name,
            role=role,
            goal=goal,
            backstory=f"A helpful {role} focused on: {goal}.",
            llm_tags=["fast"],
            tool_refs=[],
            memory_ref=None
        )
    except Exception as e:
        console.print(f"[bold red]Validation Error:[/bold red]\n{e}")
        raise typer.Exit(code=1)
        
    file_name = f"{name.lower().replace(' ', '_')}.yaml"
    dest_path = os.path.join(project_path, "agents", file_name)
    
    with open(dest_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(config.model_dump(), f)
        
    console.print(f"[bold green]Success:[/bold green] Created agent '{name}' at {dest_path}")


@app.command("new-tool")
def new_tool(
    project_path: str,
    name: str = typer.Option(..., help="Lowercase snake_case name of the tool")
):
    """
    Scaffolds a Python class stub for a BaseTool subclass in tools/.
    """
    class_name = to_camel_case(name)
    tool_content = (
        "\"\"\"\n"
        f"Custom Tool: {class_name}\n"
        "\"\"\"\n\n"
        "from agentos.core.base import BaseTool\n\n"
        f"class {class_name}(BaseTool):\n"
        f"    name: str = \"{name}\"\n"
        f"    description: str = \"TODO: Provide detailed description of this tool's behavior.\"\n\n"
        "    def run(self, **kwargs) -> str:\n"
        "        # TODO: Implement tool business logic\n"
        "        query = kwargs.get('query', '')\n"
        "        return f\"Stub tool executed with query: {query}\"\n"
    )
    
    dest_path = os.path.join(project_path, "tools", f"{name}.py")
    with open(dest_path, "w", encoding="utf-8") as f:
        f.write(tool_content)
        
    console.print(f"[bold green]Success:[/bold green] Scaffolded tool '{class_name}' at {dest_path}")


@app.command("new-crew")
def new_crew(
    project_path: str,
    name: str = typer.Option(..., help="Name of the crew"),
    agents: str = typer.Option(..., help="Comma-separated agent names to include"),
    process: str = typer.Option("sequential", help="Process type: sequential or hierarchical")
):
    """
    Creates a new crew YAML configuration validating agent names.
    """
    agent_names = [a.strip() for a in agents.split(",") if a.strip()]
    
    # Validate agent names exist
    agents_dir = os.path.join(project_path, "agents")
    existing_agents = []
    if os.path.exists(agents_dir):
        for file in glob.glob(os.path.join(agents_dir, "*.yaml")):
            with open(file, "r", encoding="utf-8") as f:
                try:
                    data = yaml.safe_load(f)
                    existing_agents.append(data.get("name"))
                except:
                    pass
                    
    for a in agent_names:
        if a not in existing_agents:
            console.print(f"[bold red]Error:[/bold red] Agent '{a}' is not defined in any YAML files under agents/.")
            raise typer.Exit(code=1)
            
    config = CrewYAMLConfig(name=name, agents=agent_names, process=process)
    dest_path = os.path.join(project_path, "crews", f"{name.lower().replace(' ', '_')}.yaml")
    
    with open(dest_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(config.model_dump(), f)
        
    console.print(f"[bold green]Success:[/bold green] Created crew '{name}' at {dest_path}")


@app.command("new-mcp-plugin")
def new_mcp_plugin(
    project_path: str,
    name: str = typer.Option(..., help="Name of the MCP plugin")
):
    """
    Scaffolds a Model Context Protocol third-party plugin directory template.
    """
    plugin_dir = os.path.join(project_path, "mcp_plugins", name)
    if os.path.exists(plugin_dir):
        console.print(f"[bold red]Error:[/bold red] Plugin directory '{name}' already exists.")
        raise typer.Exit(code=1)
        
    os.makedirs(plugin_dir, exist_ok=True)
    
    # manifest.yaml
    manifest = {
        "name": name,
        "version": "1.0.0",
        "author": "Developer",
        "permissions": [],
        "entrypoint": "plugin.MyMCPPlugin",
        "mcp_server_url": None
    }
    with open(os.path.join(plugin_dir, "manifest.yaml"), "w", encoding="utf-8") as f:
        yaml.safe_dump(manifest, f)
        
    # plugin.py
    plugin_stub = (
        "from agentos.core.base import BaseMCPPlugin, BaseTool\n"
        "from typing import List\n\n"
        "class MyMCPPlugin(BaseMCPPlugin):\n"
        "    def register_tools(self) -> List[BaseTool]:\n"
        "        # TODO: Implement and return plugin tools\n"
        "        return []\n"
    )
    with open(os.path.join(plugin_dir, "plugin.py"), "w", encoding="utf-8") as f:
        f.write(plugin_stub)
        
    console.print(f"[bold green]Success:[/bold green] Scaffolded MCP plugin at {plugin_dir}")


@app.command("validate")
def validate(project_path: str):
    """
    Validates all project YAML files against Pydantic schemas without executing them.
    """
    errors = 0
    
    # 1. Validate agentos.config.yaml
    config_file = os.path.join(project_path, "agentos.config.yaml")
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
            ProjectConfig(**data)
            console.print(f"[green]OK[/green] Config validated: {config_file}")
        except Exception as e:
            console.print(f"[bold red]ERROR in {config_file}:[/bold red]\n{e}")
            errors += 1
            
    # 2. Validate agents/
    agents_dir = os.path.join(project_path, "agents")
    if os.path.exists(agents_dir):
        for fpath in glob.glob(os.path.join(agents_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                AgentYAMLConfig(**data)
                console.print(f"[green]OK[/green] Agent validated: {fpath}")
            except Exception as e:
                console.print(f"[bold red]ERROR in {fpath}:[/bold red]\n{e}")
                errors += 1
                
    # 3. Validate crews/
    crews_dir = os.path.join(project_path, "crews")
    if os.path.exists(crews_dir):
        for fpath in glob.glob(os.path.join(crews_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                CrewYAMLConfig(**data)
                console.print(f"[green]OK[/green] Crew validated: {fpath}")
            except Exception as e:
                console.print(f"[bold red]ERROR in {fpath}:[/bold red]\n{e}")
                errors += 1
                
    # 4. Validate missions/
    missions_dir = os.path.join(project_path, "missions")
    if os.path.exists(missions_dir):
        for fpath in glob.glob(os.path.join(missions_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                MissionYAMLConfig(**data)
                console.print(f"[green]OK[/green] Mission validated: {fpath}")
            except Exception as e:
                console.print(f"[bold red]ERROR in {fpath}:[/bold red]\n{e}")
                errors += 1

    if errors > 0:
        console.print(f"\n[bold red]Validation failed with {errors} errors.[/bold red]")
        raise typer.Exit(code=1)
    else:
        console.print("\n[bold green]Validation passed successfully![/bold green]")

@app.command("list-agent-types")
def list_agent_types():
    """List all agent classes currently registered in AgentRegistry."""
    registry = AgentRegistry()
    table = Table(title="Registered Agent Types")
    table.add_column("Type Name", style="cyan")
    table.add_column("Python Class", style="magenta")
    if registry._registry:
        for name, cls in sorted(registry._registry.items()):
            table.add_row(name, f"{cls.__module__}.{cls.__qualname__}")
    else:
        table.add_row("[dim]none[/dim]", "[dim]Run a project first to trigger bootstrap[/dim]")
    console.print(table)


@app.command("list-tool-types")
def list_tool_types():
    """List all tool classes and instances currently registered in ToolRegistry."""
    registry = ToolRegistry()
    table = Table(title="Registered Tool Types")
    table.add_column("Name", style="cyan")
    table.add_column("Kind", style="green")
    table.add_column("Python Class", style="magenta")
    for name, cls in sorted(registry._registry.items()):
        table.add_row(name, "class", f"{cls.__module__}.{cls.__qualname__}")
    for name, inst in sorted(registry._instances.items()):
        table.add_row(name, "instance", type(inst).__qualname__)
    if not registry._registry and not registry._instances:
        table.add_row("[dim]none[/dim]", "", "[dim]No tools registered yet[/dim]")
    console.print(table)


# =====================================================================
# CLI COMMANDS - List Info
# =====================================================================

@app.command("list-agents")
def list_agents(project_path: str):
    """List all defined agents."""
    table = Table(title="Project Agents")
    table.add_column("Name", style="cyan")
    table.add_column("Role", style="magenta")
    table.add_column("Goal", style="green")
    
    agents_dir = os.path.join(project_path, "agents")
    if os.path.exists(agents_dir):
        for fpath in glob.glob(os.path.join(agents_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                table.add_row(data.get("name", ""), data.get("role", ""), data.get("goal", ""))
            except:
                pass
    console.print(table)


@app.command("list-tools")
def list_tools(project_path: str):
    """List all custom tools."""
    table = Table(title="Project Custom Tools")
    table.add_column("Class Name", style="cyan")
    table.add_column("File Name", style="magenta")
    
    tools_dir = os.path.join(project_path, "tools")
    if os.path.exists(tools_dir):
        for fpath in glob.glob(os.path.join(tools_dir, "*.py")):
            table.add_row(to_camel_case(os.path.basename(fpath)[:-3]), os.path.basename(fpath))
    console.print(table)


@app.command("list-crews")
def list_crews(project_path: str):
    """List all defined crews."""
    table = Table(title="Project Crews")
    table.add_column("Crew Name", style="cyan")
    table.add_column("Agents", style="magenta")
    table.add_column("Process", style="green")
    
    crews_dir = os.path.join(project_path, "crews")
    if os.path.exists(crews_dir):
        for fpath in glob.glob(os.path.join(crews_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                table.add_row(data.get("name", ""), ", ".join(data.get("agents", [])), data.get("process", "sequential"))
            except:
                pass
    console.print(table)


@app.command("list-missions")
def list_missions(project_path: str):
    """List all defined missions."""
    table = Table(title="Project Missions")
    table.add_column("Mission Name", style="cyan")
    table.add_column("Goal", style="green")
    table.add_column("Crew", style="magenta")
    
    missions_dir = os.path.join(project_path, "missions")
    if os.path.exists(missions_dir):
        for fpath in glob.glob(os.path.join(missions_dir, "*.yaml")):
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f)
                table.add_row(data.get("name", ""), data.get("goal", ""), data.get("crew", ""))
            except:
                pass
    console.print(table)

# =====================================================================
# CLI COMMANDS - Run Execution
# =====================================================================

@app.command("run")
def run_project(
    project_path: str,
    mission_name: str = typer.Option(..., "--mission", help="Name of the mission config to run"),
    resume: bool = typer.Option(False, help="Resume execution from latest checkpoint")
):
    """
    Executes a project mission, loading config, resolving tools/plugins, and checkpointing.
    """
    from agentos.core.project_ops import build_squad_from_project
    try:
        squad, mission = build_squad_from_project(project_path, mission_name)
    except Exception as e:
        console.print(f"[bold red]Error loading project/mission configuration:[/bold red] {e}")
        raise typer.Exit(code=1)
    
    # 10. Run mission
    console.print(f"[bold blue]Running mission:[/bold blue] {mission.id} (resume={resume})...")
    try:
        result = squad.run_mission(mission, resume=resume)
        console.print("\n[bold green]Mission executed successfully! Output:[/bold green]")
        console.print(result)
    except Exception as e:
        console.print(f"\n[bold red]Mission execution failed:[/bold red] {e}")
        raise typer.Exit(code=1)

# =====================================================================
# CLI COMMANDS - Natural Language Builders
# =====================================================================

@app.command("build-agent")
def build_agent(
    project_path: str,
    describe: str = typer.Option(..., help="Natural language description of the agent")
):
    """
    Proposes agent configuration via LLM and writes to agents/ after confirmation.
    """
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    llm_client = LLMClient(preferred_tags=preferred_tags)
    builder = AgentBuilder(llm_client=llm_client)
    
    console.print("[bold blue]Proposing Agent configuration via LLM...[/bold blue]")
    try:
        proposed = builder.create_from_description(describe)
    except Exception as e:
        console.print(f"[bold red]LLM Generation failed:[/bold red] {e}")
        raise typer.Exit(code=1)
        
    yaml_str = yaml.safe_dump(proposed, default_flow_style=False)
    console.print("\n[bold yellow]Proposed Agent YAML:[/bold yellow]")
    console.print(Syntax(yaml_str, "yaml", theme="monokai", line_numbers=True))
    
    confirm = typer.confirm("Do you want to write this configuration to agents/?")
    if confirm:
        file_name = f"{proposed['name'].lower().replace(' ', '_')}.yaml"
        dest_path = os.path.join(project_path, "agents", file_name)
        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(yaml_str)
        console.print(f"[bold green]Success:[/bold green] Wrote Agent config to {dest_path}")
    else:
        console.print("[yellow]Cancelled configuration write.[/yellow]")


@app.command("build-tool")
def build_tool(
    project_path: str,
    describe: str = typer.Option(..., help="Natural language description of what the tool should do")
):
    """
    Proposes custom python tool stubs via LLM and writes to tools/ after confirmation.
    """
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    llm_client = LLMClient(preferred_tags=preferred_tags)
    builder = ToolBuilder(llm_client=llm_client)
    
    console.print("[bold blue]Proposing Custom Tool stub via LLM...[/bold blue]")
    try:
        config, py_code = builder.create_from_description(describe)
    except Exception as e:
        console.print(f"[bold red]LLM Generation failed:[/bold red] {e}")
        raise typer.Exit(code=1)
        
    console.print("\n[bold yellow]Proposed Python Tool Stub Code:[/bold yellow]")
    console.print(Syntax(py_code, "python", theme="monokai", line_numbers=True))
    
    confirm = typer.confirm("Do you want to write this tool code to tools/?")
    if confirm:
        dest_path = os.path.join(project_path, "tools", f"{config['name']}.py")
        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(py_code)
        console.print(f"[bold green]Success:[/bold green] Wrote Custom Tool stub to {dest_path}")
    else:
        console.print("[yellow]Cancelled tool stub write.[/yellow]")


@app.command("build-crew")
def build_crew(
    project_path: str,
    describe: str = typer.Option(..., help="Natural language overall project goal description")
):
    """
    Proposes entire crew orchestrations (crews, agents, and task lists) via LLM.
    """
    config_file = os.path.join(project_path, "agentos.config.yaml")
    preferred_tags = ["fast"]
    if os.path.exists(config_file):
        try:
            with open(config_file, "r", encoding="utf-8") as f:
                p_cfg = yaml.safe_load(f)
                preferred_tags = p_cfg.get("preferred_tags", ["fast"])
        except:
            pass
            
    llm_client = LLMClient(preferred_tags=preferred_tags)
    builder = CrewBuilder(llm_client=llm_client)
    
    console.print("[bold blue]Proposing Crew Orchestration design via LLM...[/bold blue]")
    try:
        proposed = builder.create_from_goal(describe)
    except Exception as e:
        console.print(f"[bold red]LLM Generation failed:[/bold red] {e}")
        raise typer.Exit(code=1)
        
    json_str = json.dumps(proposed, indent=2)
    console.print("\n[bold yellow]Proposed Crew Structure (JSON):[/bold yellow]")
    console.print(Syntax(json_str, "json", theme="monokai", line_numbers=True))
    
    confirm = typer.confirm("Do you want to write these proposed Agent, Crew, and Mission configurations to disk?")
    if confirm:
        # 1. Write agents
        for a in proposed["agents"]:
            a_cfg = {
                "name": a["name"],
                "role": a["role"],
                "goal": a["goal"],
                "backstory": a["backstory"],
                "llm_tags": ["fast"],
                "tool_refs": a.get("suggested_tools", []),
                "memory_ref": None
            }
            a_file = os.path.join(project_path, "agents", f"{a['name'].lower().replace(' ', '_')}.yaml")
            with open(a_file, "w", encoding="utf-8") as f:
                yaml.safe_dump(a_cfg, f)
            console.print(f"[green]OK[/green] Wrote Agent definition: {a_file}")
            
        # 2. Write Crew
        c_names = [a["name"] for a in proposed["agents"]]
        c_cfg = {
            "name": proposed["name"],
            "agents": c_names,
            "process": proposed.get("process", "sequential")
        }
        c_file = os.path.join(project_path, "crews", f"{proposed['name'].lower().replace(' ', '_')}.yaml")
        with open(c_file, "w", encoding="utf-8") as f:
            yaml.safe_dump(c_cfg, f)
        console.print(f"[green]OK[/green] Wrote Crew definition: {c_file}")
        
        # 3. Write Mission
        m_tasks = []
        for t in proposed["tasks"]:
            m_tasks.append({
                "description": t["description"],
                "assigned_agent": t["assigned_agent"]
            })
        m_cfg = {
            "name": f"{proposed['name']}Mission",
            "goal": describe,
            "description": f"Auto-generated mission for crew: {proposed['name']}",
            "crew": proposed["name"],
            "tasks": m_tasks
        }
        m_file = os.path.join(project_path, "missions", f"{proposed['name'].lower().replace(' ', '_')}_mission.yaml")
        with open(m_file, "w", encoding="utf-8") as f:
            yaml.safe_dump(m_cfg, f)
        console.print(f"[green]OK[/green] Wrote Mission definition: {m_file}")
        
        console.print("[bold green]Success: All proposed configs written to disk successfully.[/bold green]")
    else:
        console.print("[yellow]Cancelled configuration write.[/yellow]")


# =====================================================================
# PACKAGING COMMANDS (Phase 3)
# =====================================================================

pack_app = typer.Typer(help="Build, sign, verify, and install .agentpack bundles")
app.add_typer(pack_app, name="pack")


@app.command("keygen")
def keygen(
    keys_dir: Optional[str] = typer.Option(None, help="Directory to write keys (default: ~/.agentos/keys/)"),
):
    """Generate an Ed25519 keypair for signing .agentpack files."""
    from agentos.packaging.signer import generate_keypair
    priv, pub = generate_keypair(keys_dir=keys_dir)
    console.print(f"[green]OK[/green] Private key: {priv}")
    console.print(f"[green]OK[/green] Public key:  {pub}")
    console.print("[bold yellow]WARNING: Never commit private.pem to version control.[/bold yellow]")


@pack_app.command("build")
def pack_build(
    project_path: str = typer.Argument(".", help="AgentOS project directory to pack"),
    agents: str = typer.Option("", help="Comma-separated agent names to include"),
    tools: str = typer.Option("", help="Comma-separated tool names to include"),
    crews: str = typer.Option("", help="Comma-separated crew names to include"),
    output: str = typer.Option("bundle.agentpack", help="Output .agentpack file path"),
):
    """Build a .agentpack file from a project directory."""
    from agentos.packaging.pack_format import build_pack
    include = {
        "agents": [s.strip() for s in agents.split(",") if s.strip()],
        "tools": [s.strip() for s in tools.split(",") if s.strip()],
        "crews": [s.strip() for s in crews.split(",") if s.strip()],
    }
    result = build_pack(project_path=os.path.abspath(project_path), include=include, output_path=output)
    console.print(f"[green]OK[/green] Pack built: {result}")


@pack_app.command("sign")
def pack_sign(
    pack_path: str = typer.Argument(..., help="Path to .agentpack file"),
    key: str = typer.Option(None, help="Path to private.pem (default: ~/.agentos/keys/private.pem)"),
):
    """Sign a .agentpack file with your Ed25519 private key."""
    from agentos.packaging.signer import sign_pack
    from pathlib import Path
    key_path = key or str(Path.home() / ".agentos" / "keys" / "private.pem")
    sign_pack(pack_path=pack_path, private_key_path=key_path)
    console.print(f"[green]OK[/green] Pack signed: {pack_path}")


@pack_app.command("verify")
def pack_verify(
    pack_path: str = typer.Argument(..., help="Path to .agentpack file"),
):
    """Verify the Ed25519 signature of a .agentpack file."""
    from agentos.packaging.signer import verify_pack, get_signer_fingerprint
    valid = verify_pack(pack_path)
    if valid:
        fp = get_signer_fingerprint(pack_path)
        console.print(f"[green]VALID[/green] Signature verified. Signer fingerprint: {fp}")
    else:
        console.print("[bold red]INVALID[/bold red] Signature verification failed or pack is unsigned.")
        raise typer.Exit(code=1)


@pack_app.command("install")
def pack_install(
    pack_path: str = typer.Argument(..., help="Path to .agentpack file"),
    target: str = typer.Argument(..., help="Target AgentOS project directory"),
    force: bool = typer.Option(False, "--force", help="Overwrite existing files"),
    license_key: Optional[str] = typer.Option(None, "--license-key", help="License key for commercial packs"),
):
    """Install a .agentpack into an AgentOS project directory."""
    from agentos.packaging.pack_format import install_pack
    try:
        result = install_pack(pack_path=pack_path, target_project=target, force=force, license_key=license_key)
        console.print(f"[green]OK[/green] Installed pack '{result['pack']}' v{result['version']}")
        for category, items in result["installed"].items():
            if items:
                console.print(f"  {category}: {', '.join(str(i) for i in items)}")
    except PermissionError as e:
        console.print(f"[bold red]LICENSE ERROR:[/bold red] {e}")
        raise typer.Exit(code=1)
    except FileExistsError as e:
        console.print(f"[bold red]CONFLICT:[/bold red] {e}")
        raise typer.Exit(code=1)




# =====================================================================
# PHASE 4 — WORKSTREAM B: Templates CLI
# =====================================================================

templates_app = typer.Typer(help="Manage bundled AgentOS templates")
app.add_typer(templates_app, name="templates")


@templates_app.command("list")
def templates_list():
    """List all bundled AgentOS templates."""
    from agentos.templates import list_templates
    templates = list_templates()
    table = Table("Name", "Display Name", "Description", "Tags", "Pack Ready")
    for t in templates:
        table.add_row(
            t["name"],
            t["display_name"],
            t["description"][:60] + ("…" if len(t["description"]) > 60 else ""),
            ", ".join(t["tags"]),
            "[green]✓[/green]" if t["pack_available"] else "[yellow]Build needed[/yellow]",
        )
    console.print(table)


@templates_app.command("install")
def templates_install(
    name: str = typer.Argument(..., help="Template name (e.g. research_assistant)"),
    project: str = typer.Argument(".", help="Target AgentOS project directory"),
    force: bool = typer.Option(False, "--force", help="Overwrite existing files"),
):
    """Install a bundled template into an AgentOS project."""
    from agentos.templates import install_template
    project_path = os.path.abspath(project)
    try:
        result = install_template(template_name=name, target_project=project_path, force=force)
        console.print(f"[green]OK[/green] Installed template '{name}' into {project_path}")
        for category, items in result.get("installed", {}).items():
            if items:
                console.print(f"  {category}: {', '.join(str(i) for i in items)}")
        console.print("\n[dim]Run 'agentos validate' to verify the project setup.[/dim]")
    except FileExistsError as e:
        console.print(f"[bold red]CONFLICT:[/bold red] {e}")
        console.print("[dim]Use --force to overwrite.[/dim]")
        raise typer.Exit(code=1)
    except (ValueError, FileNotFoundError) as e:
        console.print(f"[bold red]ERROR:[/bold red] {e}")
        raise typer.Exit(code=1)


# =====================================================================
# PHASE 4 — WORKSTREAM C: Federation CLI
# =====================================================================

fed_app = typer.Typer(help="Multi-Squad Federation commands")
app.add_typer(fed_app, name="federation")


@fed_app.command("new")
def new_federated_mission(
    name: str = typer.Argument(..., help="Name for the federated mission"),
    squads: str = typer.Option(..., "--squads", help="Comma-separated crew names for each stage (e.g. crew_a,crew_b)"),
    missions: str = typer.Option(..., "--missions", help="Comma-separated mission names for each stage (must match squads count)"),
    project: str = typer.Argument(".", help="AgentOS project directory"),
):
    """
    Create a new federated mission config linking multiple squads in sequence.

    Example:
        agentos federation new my-research-write --squads research_crew,writing_crew --missions research,write_report
    """
    project_path = os.path.abspath(project)
    squad_list = [s.strip() for s in squads.split(",") if s.strip()]
    mission_list = [m.strip() for m in missions.split(",") if m.strip()]

    if len(squad_list) != len(mission_list):
        console.print(f"[bold red]ERROR:[/bold red] --squads and --missions must have the same count. "
                      f"Got {len(squad_list)} squads and {len(mission_list)} missions.")
        raise typer.Exit(code=1)

    if len(squad_list) < 2:
        console.print("[bold red]ERROR:[/bold red] A federated mission requires at least 2 stages.")
        raise typer.Exit(code=1)

    stages = [{"squad_crew": s, "mission": m} for s, m in zip(squad_list, mission_list)]
    config = {"name": name, "stages": stages}

    fed_dir = os.path.join(project_path, "federated_missions")
    os.makedirs(fed_dir, exist_ok=True)
    config_path = os.path.join(fed_dir, f"{name}.yaml")

    if os.path.exists(config_path):
        console.print(f"[bold red]ERROR:[/bold red] Federated mission '{name}' already exists at {config_path}.")
        raise typer.Exit(code=1)

    with open(config_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(config, f)

    console.print(f"[green]OK[/green] Created federated mission '{name}' with {len(stages)} stages:")
    for idx, stage in enumerate(stages):
        console.print(f"  Stage {idx}: {stage['squad_crew']} / {stage['mission']}")
    console.print(f"\nRun with: [bold]agentos federation run {name} {project}[/bold]")


@fed_app.command("run")
def run_federated_mission(
    name: str = typer.Argument(..., help="Federated mission name"),
    project: str = typer.Argument(".", help="AgentOS project directory"),
    resume: bool = typer.Option(False, "--resume", help="Resume from last checkpoint (skip completed stages)"),
):
    """
    Run a federated mission: execute multiple squads sequentially with context handoff.
    """
    import asyncio
    project_path = os.path.abspath(project)

    # Load config
    config_path = os.path.join(project_path, "federated_missions", f"{name}.yaml")
    if not os.path.exists(config_path):
        console.print(f"[bold red]ERROR:[/bold red] Federated mission '{name}' not found at {config_path}")
        raise typer.Exit(code=1)

    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    stages_cfg = config.get("stages", [])
    console.print(f"\n[bold]Running federated mission '[cyan]{name}[/cyan]'[/bold] ({len(stages_cfg)} stages)\n")

    from agentos.core.federation import FederatedMission, FederationStage
    from agentos.core.project_ops import build_squad_from_project

    checkpoint_db = os.path.join(project_path, "checkpoints", "run_history.db")
    store = SQLiteCheckpointStore(db_path=checkpoint_db)

    try:
        stages = []
        for idx, stage_cfg in enumerate(stages_cfg):
            mission_name = stage_cfg["mission"]
            console.print(f"  Building stage {idx}: {stage_cfg['squad_crew']} / {mission_name}")
            squad, mission = build_squad_from_project(project_path, mission_name)
            stages.append(FederationStage(
                squad=squad,
                mission=mission,
                stage_index=idx,
                name=f"{stage_cfg['squad_crew']}/{mission_name}",
            ))

        fed = FederatedMission(federation_id=name, stages=stages, checkpoint_store=store)
        result = asyncio.run(fed.run())

        console.print(f"\n[green]✓ Federation complete![/green] {result['stages_completed']}/{result['total_stages']} stages ran.")
        console.print("\n[bold]Final output:[/bold]")
        console.print(result.get("final_output", "(no output)"))

    except RuntimeError as e:
        console.print(f"\n[bold red]Federation failed:[/bold red] {e}")
        console.print("[dim]Completed stages are checkpointed. Re-run with the same name to resume.[/dim]")
        raise typer.Exit(code=1)
    except Exception as e:
        console.print(f"\n[bold red]Unexpected error:[/bold red] {e}")
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
