"""
ReportGenerator - Generates machine-readable and human-readable execution run reports for AgentOS-SWE (M7).
"""

import json
import logging
from datetime import datetime
from typing import Dict, Any, Optional

from agentos_swe.observability.models import RunReport
from agentos_swe.observability.tracer import TraceCollector
from agentos_swe.security.secret_protection import SecretProtection

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates structured JSON and Markdown execution run reports from a TraceCollector.
    """

    def generate_run_report(
        self,
        collector: TraceCollector,
        repository_name: str = "Unknown Repo",
        commit_ref: Optional[str] = None,
        start_time: Optional[str] = None,
    ) -> RunReport:
        start_t = start_time or (collector.events[0].timestamp if collector.events else datetime.now().isoformat())
        end_t = collector.events[-1].timestamp if collector.events else datetime.now().isoformat()

        total_tokens = sum(e.tokens for e in collector.events)
        total_latency = sum(e.latency_sec for e in collector.events)
        total_cost = sum(e.cost_est for e in collector.events)

        report = RunReport(
            repository_name=repository_name,
            commit_ref=commit_ref,
            start_time=start_t,
            end_time=end_t,
            total_duration_sec=total_latency,
            finding_metrics=collector.finding_metrics,
            repair_metrics=collector.repair_metrics,
            agent_metrics=collector.agent_metrics,
            fallback_count=collector.fallback_count,
            checkpoint_recoveries=collector.checkpoint_recoveries,
            total_tokens=total_tokens,
            total_cost_est=total_cost,
            trace_events_count=len(collector.events),
        )
        return report

    def render_markdown_report(self, report: RunReport) -> str:
        f_m = report.finding_metrics
        r_m = report.repair_metrics

        agent_rows = []
        for name, a in report.agent_metrics.items():
            agent_rows.append(
                f"| `{name}` | {a.execution_count} | {a.success_count} | {a.failure_count} | {a.fallback_count} | {a.total_tokens} | {a.total_duration_sec:.2f}s |"
            )
        agent_table = "\n".join(agent_rows) if agent_rows else "| None | 0 | 0 | 0 | 0 | 0 | 0s |"

        md = f"""# 📊 AgentOS-SWE Execution Run Report

### 📌 Execution Summary
- **Repository**: `{report.repository_name}`
- **Git Commit Ref**: `{report.commit_ref or 'N/A'}`
- **Start Time**: `{report.start_time}`
- **End Time**: `{report.end_time}`
- **Total Duration**: `{report.total_duration_sec:.2f}s`
- **Total Trace Events**: `{report.trace_events_count}`

---

### 🔍 Finding Lifecycle Metrics
- **Total Discovered**: `{f_m.total_discovered}`
- **Confirmed True Positives**: `{f_m.confirmed}`
- **Rejected False Positives**: `{f_m.rejected}`
- **Inconclusive Findings**: `{f_m.inconclusive}`

---

### 🛠️ Controlled Repair Metrics
- **Patches Generated**: `{r_m.patches_generated}`
- **Reproduction Tests Passed**: `{r_m.reproduction_pass}`
- **Regression Tests Passed**: `{r_m.regression_pass}`
- **Independent Reviews Approved**: `{r_m.independent_review_pass}`
- **Validated Patches Produced**: `{r_m.validated_patches}`

---

### 🛡️ System Resilience & Resources
- **LLM Router Fallbacks**: `{report.fallback_count}`
- **Checkpoint Recoveries**: `{report.checkpoint_recoveries}`
- **Total Tokens Consumed**: `{report.total_tokens}`
- **Estimated Cost**: `${report.total_cost_est:.4f}`

---

### 🤖 Agent Execution Breakdown
| Agent | Runs | Success | Fail | Fallback | Tokens | Latency |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
{agent_table}

---
*Report generated by **AgentOS-SWE (Autonomous Software Verification and Repair System)**.*
"""
        return SecretProtection.sanitize_text(md)
